Class MRMonstC_ReplaceeOptionMenu: OptionMenu
{
	int CurIndex;
	Array<int> SelectedItems;
	Override Void Init(Menu parent, OptionMenuDescriptor desc)
	{
		Super.Init(Parent, Desc);
		
		mDesc.mItems.Clear();
		
		Let Handler = MRMonstC_Handler(StaticEventHandler.Find("MRMonstC_Handler"));
		if(!Handler)Return;
		
		For(int i=0;i<Handler.Lists.Size();i++){
			OptionMenuItemMRMonstC_ReplaceeSelect a = New('OptionMenuItemMRMonstC_ReplaceeSelect');
			
			a.Who = Handler.ListNames[i];
			if((Class<Actor>)(a.Who)){
				a.mLabel = GetDefaultByType((Class<Actor>)(a.Who)).GetTag();
			}
			a.Index = i;
			a.Menue = Self;
			mDesc.mItems.Push(a);
		}
		
		mDesc.mItems.Push(New('OptionMenuItemStaticText'));
		Let Temp = New('OptionMenuItemOption');
		Temp.Init("$MRMonstC_DisplayAmbush", "MRMonstC_DisplayAmbush", "YesNo");
		mDesc.mItems.Push(Temp);
		Temp = New('OptionMenuItemOption');
		Temp.Init("$MRMonstC_DisplayMisc", "MRMonstC_DisplayMisc", "YesNo");
		mDesc.mItems.Push(Temp);
		/*mDesc.mItems.Push(New('OptionMenuItemStaticText'));
		Let Temp1 = New('OptionMenuItemSubMenu');
		Temp1.Init("$MRMonstC_PressetsOptionMenu", "MRMonstC_PressetsOptionMenu");
		mDesc.mItems.Push(Temp1);*/
	}
}

Class OptionMenuItemMRMonstC_ReplaceeSelect: OptionMenuItemSubmenu
{
	MRMonstC_ReplaceeOptionMenu Menue;
	String Who;
	int Index;
	
	Override bool Activate()
	{
		if(Menue)Menue.CurIndex = Index;
		Menu.MenuSound("menu/advance");
		Menu.SetMenu("MRMonstC_ReplacementOptionMenu", Index);
		return true;
	}
}

Class MRMonstC_ReplacementOptionMenu: OptionMenu
{
	int Index;
	Bool Opened[10000];
	Array<OptionMenuItemMRMonstC_SpoilerList> Spoilers;
	Override Void Init(Menu parent, OptionMenuDescriptor desc)
	{
		Super.Init(Parent, Desc);
		if(!mParentMenu)Return;
		
		Let Parent = MRMonstC_ReplaceeOptionMenu(mParentMenu);
		Index = Parent.CurIndex;

		if(Parent.SelectedItems.Size()>Index)mDesc.mSelectedItem = Parent.SelectedItems[Index];
		else mDesc.mSelectedItem = 0;
		
		mDesc.Reset();
		
		SetUpSpoilers();
		UpdateItems();
	}
	
	Override bool MenuEvent (int mkey, bool fromcontroller)
	{
		switch (mkey)
		{
			case MKEY_Back:
			{
				Let Parent = MRMonstC_ReplaceeOptionMenu(mParentMenu);
				if(Parent.SelectedItems.Size()>Index)Parent.SelectedItems[Index] = mDesc.mSelectedItem;
				else Parent.SelectedItems.Insert(Index, mDesc.mSelectedItem);
				Close();
				let m = GetCurrentMenu();
				MenuSound(m != null ? "menu/backup" : "menu/clear");
				if (!m) menuDelegate.MenuDismissed();
				return true;
			}
		}
		return Super.MenuEvent(mkey, fromcontroller);
	}
	
	Void SetUpSpoilers()
	{
		Let Handler = MRMonstC_Handler(StaticEventHandler.Find("MRMonstC_Handler"));
		if(!Handler)Return;
		
		Spoilers.Clear();
		
		Array<String> Names;
		For(int i=0;i<Handler.ListNames.Size();i++){
			if(Handler.Lists[i].Replaceable)Names.Push(StringTable.Localize(GetDefaultByType(Handler.Lists[i].Replaceable).GetTag()));
			else Names.Push(Handler.ListNames[i]);
		}
		
		int ItemIndex;
		Let Spoiler = New('OptionMenuItemMRMonstC_SpoilerList');
		Spoiler.Menue = Self;
		Spoiler.Index = ItemIndex;
		Spoiler.Who = Names[Index];
		Spoiler.Who = "\c-"..Spoiler.Who.MakeUpper();
		Opened[ItemIndex] = 1;
	
		if(Opened[ItemIndex])Spoiler.mLabel = "$MRMonstC_Menu_HideList";
		else Spoiler.mLabel = "$MRMonstC_Menu_ShowList";
		Spoiler.mLabel = StringTable.Localize(Spoiler.mLabel)..Spoiler.Who;
		Spoilers.Push(Spoiler);
		
		Names.Delete(Index);
		
		ItemIndex++;
		
		For(int i=1;i<Handler.Lists.Size();i++){
			Let Spoiler = New('OptionMenuItemMRMonstC_SpoilerList');
			Spoiler.Menue = Self;
			Spoiler.Index = ItemIndex;
			Spoiler.Who = Names[i-1];
			Spoiler.Who = "\c-"..Spoiler.Who.MakeUpper();
			Opened[ItemIndex] = 0;
		
			if(Opened[ItemIndex])Spoiler.mLabel = "$MRMonstC_Menu_HideList";
			else Spoiler.mLabel = "$MRMonstC_Menu_ShowList";
			Spoiler.mLabel = StringTable.Localize(Spoiler.mLabel)..Spoiler.Who;
			Spoilers.Push(Spoiler);
			
			ItemIndex++;
		}
		
		For(int i=0;i<Handler.MiscLists.Size();i++){
			Let Spoiler = New('OptionMenuItemMRMonstC_SpoilerList');
			Spoiler.Menue = Self;
			Spoiler.Index = ItemIndex;
			Spoiler.Who = Handler.MiscLists[i].Replacers[0].GetClassName();
			Spoiler.Who = "\c-"..Spoiler.Who;
			Opened[ItemIndex] = 0;
		
			if(Opened[ItemIndex])Spoiler.mLabel = "$MRMonstC_Menu_HideList";
			else Spoiler.mLabel = "$MRMonstC_Menu_ShowList";
			Spoiler.mLabel = StringTable.Localize(Spoiler.mLabel)..Spoiler.Who;
			Spoilers.Push(Spoiler);
			
			ItemIndex++;
		}
	}
	
	Void UpdateItems()
	{
		mDesc.mItems.Clear();
		Let Handler = MRMonstC_Handler(StaticEventHandler.Find("MRMonstC_Handler"));
		if(!Handler)Return;
		
		Array<MRMonstC_Replace> Lists, AmbushLists;
		String Replacing = Handler.ListNames[Index];
		
		Lists.Copy(Handler.Lists);
		AmbushLists.Copy(Handler.AmbushLists);
		
		Let List = Lists[Index];
		
		mDesc.mTitle = String.Format(StringTable.Localize("$MRMonstC_Menu_Repalce"),
			List.Replaceable?StringTable.Localize(GetDefaultByType(List.Replaceable).GetTag()):Replacing);
				
		Let Temp = New('OptionMenuItemMRMonstC_ClearReplaceList');
		Temp.mLabel = "$MRMonstC_Menu_Reset";
		Temp.Which = Replacing;
		Temp.Menue = Self;
		mDesc.mItems.Push(Temp);
		
		mDesc.mItems.Push(New('OptionMenuItemStaticText'));
		int ItemIndex = 0;
		AddList(List, Replacing, ItemIndex, AmbushLists[Index]);
		ItemIndex++;
		
		Lists.Delete(Index);
		AmbushLists.Delete(Index);
		
		mDesc.mItems.Push(New('OptionMenuItemStaticText'));
		
		Let Text = New('OptionMenuItemStaticText');
		Text.mLabel = "$MRMonstC_Menu_OtherLists";
		Text.mColor = Font.CR_Fire;
		mDesc.mItems.Push(Text);
		
		For(int i=0;i<Lists.Size();i++){
			AddList(Lists[i], Replacing, ItemIndex, AmbushLists[i]);
			ItemIndex++;
		}
		
		if(!CVar.FindCVar("MRMonstC_DisplayMisc").GetBool())Return;
		
		Text = New('OptionMenuItemStaticText');
		Text.mLabel = "$MRMonstC_Menu_MiscLists";
		Text.mColor = Font.CR_Fire;
		mDesc.mItems.Push(Text);
		
		For(int i=0;i<Handler.MiscLists.Size();i++){
			AddList(Handler.MiscLists[i], Replacing, ItemIndex);
			ItemIndex++;
		}
	}
	
	Void AddList(MRMonstC_Replace List, String ListName, int Index, MRMonstC_Replace AmbushList=Null)
	{
		mDesc.mItems.Push(Spoilers[Index]);
		
		if(!Opened[Index])Return;
		
		Let Temp = New('OptionMenuItemMRMonstC_ActivateList');
		Temp.Menue = Self;
		Temp.Index = Index;
		Temp.SetName();
		mDesc.mItems.Push(Temp);

		//mDesc.mItems.Push(New('OptionMenuItemStaticText'));
		
		For(int i=0;i<List.Replacers.Size();i++){
			OptionMenuItemMRMonstC_ReplacementSelect a = New('OptionMenuItemMRMonstC_ReplacementSelect');
			a.Replacing = ListName;
			a.Who = List.Replacers[i].GetClassName();
						
			if(List.Replacers[i]){
				a.mLabel = GetDefaultByType(List.Replacers[i]).GetTag().." \cd("..List.Replacers[i].GetClassName()..")";
				if(!GetDefaultByType(List.Replacers[i]).bIsMonster||List.Replacers[i] is 'RandomSpawner')a.mLabel = "? "..a.mLabel;
				Let CVa = CVar.GetCVar("MRMonstC_Replace_"..a.Replacing);
				
				if(CVa && CVa.GetString().IndexOf(a.Who..",")>-1){
					a.mLabel = "\cf"..a.mLabel;
				}
			}
			Temp.Items.Push(a);
			mDesc.mItems.Push(a);
		}
		
		if(CVar.FindCVar("MRMonstC_DisplayAmbush").GetBool() && AmbushList){
			Let Text = New('OptionMenuItemStaticText');
			Text.mLabel = "$MRMonstC_Menu_Ambush";
			Text.mColor = Font.CR_PURPLE;
			mDesc.mItems.Push(Text);
			
			For(int i=0;i<AmbushList.Replacers.Size();i++){
				OptionMenuItemMRMonstC_ReplacementSelect a = New('OptionMenuItemMRMonstC_ReplacementSelect');
				a.Replacing = ListName;
				a.Who = AmbushList.Replacers[i].GetClassName();
							
				if(AmbushList.Replacers[i]){
					a.mLabel = GetDefaultByType(AmbushList.Replacers[i]).GetTag().." \cd("..a.Who..")";
					if(!GetDefaultByType(AmbushList.Replacers[i]).bIsMonster||AmbushList.Replacers[i] is 'RandomSpawner')a.mLabel = "? "..a.mLabel;
					
					Let CVa = CVar.GetCVar("MRMonstC_Replace_"..a.Replacing);
					
					if(CVa && CVa.GetString().IndexOf(a.Who..",")>-1){
						a.mLabel = "\cf"..a.mLabel;
					}
				}
				
				Temp.Items.Push(a);
				mDesc.mItems.Push(a);
			}
		}
		mDesc.mItems.Push(New('OptionMenuItemStaticText'));
	}
	
	Override Void Drawer()
	{
		Super.Drawer();
		
		int Item = mDesc.mSelectedItem;
		
		if(Item<0 || Item>=mDesc.mItems.Size())Return;
		
		if(!OptionMenuItemMRMonstC_ReplacementSelect(mDesc.mItems[Item]))Return;
		
		Class<Actor> Display = OptionMenuItemMRMonstC_ReplacementSelect(mDesc.mItems[Item]).Who;
		
		if(!Display)Return;
		
		TextureID Sprite;
		Vector2 Scale;
		Bool Flip;
		Let Stat = GetDefaultByType(Display).FindState("Spawn");
		
		if(!Stat)Return;
		
		[Sprite, Flip, Scale] = Stat.GetSpriteTexture(0, 0, GetDefaultByType(Display).Scale);
		
		int Emerg;
		While(((!Sprite.IsValid()||Texman.GetName(Sprite) == "TNT1A0")) && Stat.NextState!=Null)
		{
			if(emerg>50)Break;
			
			Stat = Stat.NextState;
			[Sprite, Flip, Scale] = Stat.GetSpriteTexture(0, 0, GetDefaultByType(Display).Scale);
			emerg++;
		}
				
		Vector2 Size = Texman.GetScaledSize(Sprite);

		Scale.X *= CleanXfac * Size.X;
		Scale.Y *= CleanYfac * Size.Y;
		
		Double Fit = CleanXFac*100;
		
		if(Scale.X>Scale.Y){
			Scale.Y *= Fit/Scale.X;
			Scale.X *= Fit/Scale.X;
		}
		else {
			Scale.X *= Fit/Scale.Y;
			Scale.Y *= Fit/Scale.Y;
		}
		
		Double x = int(120) * CleanXfac + (screen.GetWidth() >> 1);
		Double y = Screen.GetHeight()*.6;
		
		Bool Ambush = GetDefaultByType(Display).bAmbush || GetDefaultByType(Display).bStealth;
		
		Screen.DrawTexture(Sprite, false, X, Y,
			DTA_DestWidthF, Scale.X,
			DTA_DestHeightF, Scale.Y,
			DTA_FlipX, Flip,
			DTA_Alpha, Ambush?1:GetDefaultByType(Display).Alpha,
			DTA_LegacyRenderStyle, Ambush?STYLE_Normal:GetDefaultByType(Display).GetRenderStyle());
	}
}

Class OptionMenuItemMRMonstC_SpoilerList: OptionMenuItemSubMenu
{
	String Who;
	int Index;
	MRMonstC_ReplacementOptionMenu Menue;
		
	Override Bool Activate()
	{
		if(!Menue)Return False;
		
		Menu.MenuSound("menu/change");
		Menue.Opened[Index] = !Menue.Opened[Index];
		
		if(Menue.Opened[Index])mLabel = "$MRMonstC_Menu_HideList";
		else mLabel = "$MRMonstC_Menu_ShowList";
		
		mLabel = StringTable.Localize(mLabel)..Who;
		
		Menue.UpdateItems();
		Return True;
	}
}

Class OptionMenuItemMRMonstC_ActivateList: OptionMenuItemSubMenu
{
	int Index;
	MRMonstC_ReplacementOptionMenu Menue;
	Array<OptionMenuItemMRMonstC_ReplacementSelect> Items;
	
	Void SetName(){mLabel = "$MRMonstC_Menu_ActivateThisList";}
	
	Override Bool Activate()
	{
		if(!Menue)Return false;
		
		Let CVa = CVar.GetCVar("MRMonstC_Replace_"..Items[0].Replacing);
		if(!CVa)Return false;
		
		String CVaS = CVa.GetString();
		
		
		Menu.MenuSound("menu/change");
		
		Bool Active = true;
		For(int i=0;i<Items.Size();i++){
			if(CVaS.IndexOf(Items[i].Who..",")<0){Active = false;Break;}
		}
		
		if(!Active)For(int i=0;i<Items.Size();i++) {
			
			if(CVaS.IndexOf(Items[i].Who..",")<0)
			{
				CVaS = CVaS..Items[i].Who..",";
				Items[i].mLabel = "\cf"..Items[i].mLabel;
			}
		}
		
		else {
			For(int i=0;i<Items.Size();i++){
				Items[i].mLabel.Replace("\cf", "");
				CVaS.Replace(Items[i].Who..",", "");
			}
		}
		
		CVa.SetString(CVaS);
		Return true;
	}
}

Class OptionMenuItemMRMonstC_ReplacementSelect: OptionMenuItemSubmenu
{
	String Who, Replacing;
	
	Override bool Activate()
	{
		Let CVa = CVar.GetCVar("MRMonstC_Replace_"..Replacing);
		if(!CVa)Return false;
		
		Menu.MenuSound("menu/change");
		if(CVa.GetString().IndexOf(Who..",")<0)
		{
			CVa.SetString(CVa.GetString()..Who..",");
			mLabel = "\cf"..mLabel;
		}
		else
		{
			String List = CVa.GetString();
			List.Replace(Who..",", "");
			CVa.SetString(List);
			mLabel.Replace("\cf", "");
		}
				
		return true;
	}
}

Class OptionMenuItemMRMonstC_ClearReplaceList: OptionMenuItemSubmenu
{
	String Which;
	MRMonstC_ReplacementOptionMenu Menue;
	
	Override Bool Activate()
	{
		Menu.MenuSound("menu/advance");
		
		Let CVa = CVar.GetCVar("MRMonstC_Replace_"..Which);
		if(!CVa)Return true;
		
		CVa.SetString("");
		
		if(!Menue)Return true;
		
		For(int i=0;i<Menue.mDesc.mItems.Size();i++){
			Let a = OptionMenuItemMRMonstC_ReplacementSelect(Menue.mDesc.mItems[i]);
			if(!a)Continue;
			
			a.mLabel.Replace("\cf", "");
		}
		
		Return true;
	}
}