Class MRMonstC_PressetsOptionMenu: OptionMenu
{
	Override Void Init(Menu parent, OptionMenuDescriptor desc)
	{
		Super.Init(Parent, Desc);
		
		UpdatePressets();
	}
	
	Void UpdatePressets()
	{
		mDesc.mItems.Clear();
		
		{
			Let Temp = New('OptionMenuItemMRMonstC_NewPresset');
			Temp.Init("$MRMonstC_NewPresset", "");
			Temp.Menue = Self;
			mDesc.mItems.Push(Temp);
		}
		
		mDesc.mItems.Push(New('OptionMenuItemStaticText'));
				
		String PressetList = CVar.FindCVar("MRMonstC_PressetNames").GetString();
		Array<String> Pressets;
		
		PressetList.DeleteLastCharacter();
		PressetList.Split(Pressets, ",");
		
		For(int i=0;i<Pressets.Size();i++){
			Let a = New('OptionMenuItemMRMonstC_Presset');
			a._Name = Pressets[i];
			a.Init(Pressets[i], "");
			a.Menue = Self;
			mDesc.mItems.Push(a);
		}
	}
}

Class OptionMenuItemMRMonstC_NewPresset: OptionMenuFieldBase
{
	TextEnterMenu mEnter;
	OptionMenuItemMRMonstC_NewPresset Init (String label, Name command, CVar graycheck = null, int graycheckVal = 0)
	{
		Super.Init(label, command, graycheck, graycheckVal);
		mEnter = null;
		return self;
	}
	override String Represent()
	{
		if (mEnter) return mEnter.GetText() .. Menu.OptionFont().GetCursor();
		else 
		{
			bool b;
			String s;
			[b, s] = GetString(0);
			return s;
		}
	}
	override int Draw(OptionMenuDescriptor desc, int y, int indent, bool selected)
	{
		if (mEnter)
		{
			// reposition the text so that the cursor is visible when in entering mode.
			String text = Represent();
			int tlen = Menu.OptionWidth(text, false) * CleanXfac_1;
			int newindent = screen.GetWidth() - tlen - CursorSpace();
			if (newindent < indent) indent = newindent;
		}
		return Super.Draw(desc, y, indent, selected);
	}
	
	MRMonstC_PressetsOptionMenu Menue;

	override bool MenuEvent (int mkey, bool fromcontroller)
	{
		if (mkey == Menu.MKEY_Enter)
		{
			bool b;
			String s;
			[b, s] = GetString(0);
			Menu.MenuSound("menu/choose");
			mEnter = TextEnterMenu.OpenTextEnter(Menu.GetCurrentMenu(), Menu.OptionFont(), s, -1, fromcontroller);
			mEnter.ActivateMenu();
			return true;
		}
		else if (mkey == Menu.MKEY_Input)
		{
			AddPresset(mEnter.GetText());
			mEnter = null;
			Menue.UpdatePressets();
			return true;
		}
		else if (mkey == Menu.MKEY_Abort)
		{
			mEnter = null;
			return true;
		}
		
		return Super.MenuEvent(mkey, fromcontroller);
	}
	
	Void AddPresset(String PresName)
	{
		if(PresName.Length()<1)Return;
		
		Let Handler = MRMonstC_Handler(StaticEventHandler.Find("MRMonstC_Handler"));
		if(!Handler)Return;
				
		For(int i=0;i<Handler.Lists.Size();i++){
			Let List = Handler.Lists[i];
			if(!List.Replaceable)Continue;
			
			String Clas = List.Replaceable.GetClassName();
			if(!CVar.GetCVar("MRMonstC_Replace_"..Clas) || !CVar.FindCVar("MRMonstC_Pressets_"..Clas))Continue;
			
			String CVa = CVar.GetCVar("MRMonstC_Replace_"..Clas).GetString();
			String Pressets = CVar.FindCVar("MRMonstC_Pressets_"..Clas).GetString();
			
			String Presset = PresName.."{"..CVa.."}";
			
			if(Pressets.IndexOf(PresName.."{")>-1){
				String Left, Right;
				Left = Pressets.Left(Pressets.IndexOf(PresName.."{"));
				Right = Pressets.Mid(Pressets.IndexOf(PresName.."{"));
				Right = Right.Mid(Right.IndexOf("}")+1);
				Pressets = Left..Presset..Right;
			}
			else Pressets = Pressets..Presset;
			
			CVar.FindCVar("MRMonstC_Pressets_"..Clas).SetString(Pressets);
		}
		
		Let CVa = CVar.FindCVar("MRMonstC_PressetNames");
		
		if(CVa.GetString().IndexOf(PresName..",")>-1)Return;
		else CVa.SetString(CVa.GetString()..PresName..",");
	}
}

Class OptionMenuItemMRMonstC_Presset: OptionMenuItemSubMenu
{
	String _Name;
	MRMonstC_PressetsOptionMenu Menue;
	
	Override Bool Activate()
	{
		Let Handler = MRMonstC_Handler(StaticEventHandler.Find("MRMonstC_Handler"));
		if(!Handler)Return false;
				
		For(int i=0;i<Handler.Lists.Size();i++){
			if(!Handler.Lists[i].Replaceable)Continue;
			
			String Clas = Handler.Lists[i].Replaceable.GetClassName();
			
			Let Pressets = CVar.FindCVar("MRMonstC_Pressets_"..Clas);
			if(!Pressets)Continue;
			
			String Presset = Pressets.GetString();
			Presset = Presset.Mid(Presset.IndexOf(_Name.."{"));
			Presset = Presset.Mid(Presset.IndexOf("{")+1);
			Presset = Presset.Left(Presset.IndexOf("}"));
						
			CVar.GetCVar("MRMonstC_Replace_"..Clas).SetString(Presset);
		}
		
		Menu.MenuSound("menu/change");
		Return true;
	}
	
	override bool MenuEvent (int mkey, bool fromcontroller)
	{
		if(mkey != Menu.MKEY_Clear)Return Super.MenuEvent(mkey, fromcontroller);
		
		Let Handler = MRMonstC_Handler(StaticEventHandler.Find("MRMonstC_Handler"));
		if(!Handler)Return false;
		
		For(int i=0;i<Handler.Lists.Size();i++)
		{
			if(!Handler.Lists[i].Replaceable)Continue;
			
			String Clas = Handler.Lists[i].Replaceable.GetClassName();
			
			Let Pressets = CVar.FindCVar("MRMonstC_Pressets_"..Clas);
			if(!Pressets)Continue;
			
			String Presset = Pressets.GetString();
			if(Presset.IndexOf(_Name.."{")<0)Continue;
			String Left, Right;
			Left = Presset.Left(Presset.IndexOf(_Name.."{"));
			Right = Presset.Mid(Presset.IndexOf(_Name.."{"));
			Right = Right.Mid(Right.Indexof("}")+1);
			Presset = Left..Right;
			
			CVar.GetCVar("MRMonstC_Replace_"..Clas).SetString(Presset);
		}
		Let CVa = CVar.FindCVar("MRMonstC_PressetNames");
		String Pressets = CVa.GetString();
		
		Pressets.Replace(_Name..",", "");
		
		CVa.SetString(Pressets);
		
		Menu.MenuSound("menu/change");
		
		Destroy();
		
		Menue.UpdatePressets();
		
		Return false;
	}
}