Class MRMonstC_Replace: Object Play
{
	Class<Actor> Replaceable;//Actor being replaced
	Array< Class<Actor> > Replacers;//Actors that will be displayed in the menu
	//Array< Class<Actor> > Actors;
	Array< Class<Actor> > Spawning;//Actors that will replace the actor
}

Extend Class MRMonstC_Handler
{
	Array<MRMonstC_Replace> Lists, AmbushLists, MiscLists;
	Array<String> ListNames, AmbushListNames;
		
	
	Void ReadReplaceables(in out Array<String> Actors, String Data = "MRMonstCList")
	{
		Array< Class<Actor> > MiscMonsters;
		
		For(int i=0;i<AllActorClasses.Size();i++){
			if(GetDefaultByType(AllActorClasses[i]).bIsMonster)MiscMonsters.Push(AllActorClasses[i]);
		}
		
		Array<String> Files;
		int LumpNum = 0;
		While(LumpNum>-1)
		{
			int TempLump = Wads.FindLump(Data, LumpNum+1);
			if(TempLump==-1)Break;
			else {
				LumpNum = TempLump;
				Files.Push(Wads.ReadLump(LumpNum));
			}
		}
			
		For(int i=0;i<Files.Size();i++){
			String File = Files[i];

			Lump_ClearComments(File);
			
			File.Replace("\r","");
			
			Array<String> Lines;
			File.Split(Lines, "\n");
			
			For(int i1=0;i1<Lines.Size();i1++){
				Class<Actor> Act = Lines[i1];
				if(Act && ListNames.Find(Lines[i1]) == ListNames.Size()){
					ListNames.Push(Lines[i1]);
					Let a = CreateList(Act, MiscMonsters);
					Lists.Push(a);
					
					Class<Actor> Ambush = "Stealth"..Lines[i1];
					if(Ambush){
						AmbushListNames.Push("Stealth"..Lines[i1]);
						Let a = CreateList(Act, MiscMonsters, Ambush);
						AmbushLists.Push(a);
					}
					else {
						AmbushListNames.Push("None");
						AmbushLists.Push(Null);
					}
				}
			}
		}
				
		While(MiscMonsters.Size()>0){
			Let a = CreateMiscList(MiscMonsters);
			if(a)MiscLists.Push(a);
		}
	}
	
	MRMonstC_Replace CreateList(Class<Actor> Act, in out Array< Class<Actor> > MiscMonsters, Class<Actor> Ambush = Null)
	{
		MRMonstC_Replace List = New('MRMonstC_Replace');
		List.Replaceable = Act;
		
		For(int i=0;i<AllActorClasses.Size();i++){
			Let Clas = AllActorClasses[i];
			
			if(Ambush){
				if(Actor.GetReplacee(Clas) == Ambush){
					List.Replacers.Push(Clas);
					if(MiscMonsters.Find(Clas)!=MiscMonsters.Size())MiscMonsters.Delete(MiscMonsters.Find(Clas));
					Continue;
				}
				if(Clas is Act && (GetDefaultByType(Clas).bStealth || GetDefaultByType(Clas).bAmbush)){
					String Nam = Clas.GetClassName();
					Nam = Nam.MakeLower();
					if(Nam.IndexOf("mrmonstc_")<0 && Nam.IndexOf("dead")!=0){
						List.Replacers.Push(Clas);
						if(MiscMonsters.Find(Clas)!=MiscMonsters.Size())MiscMonsters.Delete(MiscMonsters.Find(Clas));
					}
				}
				Continue;
			}
			
			if(Actor.GetReplacee(Clas) == Act){
				List.Replacers.Push(Clas);
				if(MiscMonsters.Find(Clas)!=MiscMonsters.Size())MiscMonsters.Delete(MiscMonsters.Find(Clas));
			}
			else if(Clas is Act && !GetDefaultByType(Clas).bStealth && !GetDefaultByType(Clas).bAmbush){
				String Nam = Clas.GetClassName();
				Nam = Nam.MakeLower();
				if(Nam.IndexOf("mrmonstc_")<0 && Nam.IndexOf("dead")!=0){
					List.Replacers.Push(Clas);
					if(MiscMonsters.Find(Clas)!=MiscMonsters.Size())MiscMonsters.Delete(MiscMonsters.Find(Clas));
				}
			}
		}
		
		/*For(int i=0;i<List.Replacers.Size();i++){
			if(List.Replacers[i] is 'RandomSpawner'){
				Class<RandomSpawner> Spawner = List.Replacers[i].GetClassName();
				
				DropItem First, Item;
				First = GetDefaultByType(Spawner).GetDropItems();
				Item = First.Next;
				Class<Actor> mo;
				
				if(First.Name && (class<Actor>)(First.Name)){
					List.Actors.Push((class<Actor>)(First.Name));
				}
				
				While(Item && Item!=First){
					if(Item.Name && (mo = (Class<Actor>)(Item.Name))){
						List.Actors.Push(mo);
					}
					Item = Item.Next;
				}
			}
			else List.Actors.Push(List.Replacers[i]);
		}*/
		Return List;
	}
	
	MRMonstC_Replace CreateMiscList(in out Array< Class<Actor> > Arr)
	{
		String Nam = Arr[0].GetClassName();
		if(Nam.IndexOf("MRMonstC_")>-1){
			Arr.Delete(0);
			Return Null;
		}
		Let List = New('MRMonstC_Replace');
		Class<Actor> Clas = Arr[0];
		Arr.Delete(0);
		List.Replacers.Push(Clas);
		
		For(int i=0;i<Arr.Size();i++){
			Let Check = Arr[i];
			
			if(Check is Clas){
				List.Replacers.Push(Check);
				Arr.Delete(i);
				i--;
			}
		}
		
		Return List;
	}
}